# Add court slugs to the block list if they do not want to take part in
# the online service or to temporarily stop them from receiving applications.
#
blocklist:
  - blocklisted-slug-example

# Add court slugs to the centralisation list.
# Currently centralisation is disabled for any court not in this list.
#
centralisation:
  # First rollout - 02/03/2021
  - brighton-county-court
  - chelmsford-county-and-family-court
  - leeds-combined-court-centre
  - medway-county-court-and-family-court
  - west-london-family-court
  # Second rollout - 11/03/2021
  - manchester-civil-justice-centre-civil-and-family-courts
  # Third rollout - 23/03/2021
  - slough-county-court-and-family-court
  - norwich-combined-court-centre
  - milton-keynes-county-court-and-family-court
  - peterborough-combined-court-centre
  - staines-county-court-and-family-court
  - watford-county-court-and-family-court
  - guildford-county-court-and-family-court
  - reading-county-court-and-family-court
  - oxford-combined-court-centre
  - luton-justice-centre
  # 4th rollout - 22/04/2021
  - carlisle-combined-court
  - barrow-in-furness-county-court-and-family-court
  - preston-crown-court-and-family-court-sessions-house
